# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "07e2698ea30ed8908b2c6a7a1228e95c"
application_url = "https://market-shipping-threshold-app.vercel.app"
embedded = false
name = "Market Shipping Threshold App"

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_markets,write_app_proxy,read_shipping,read_discounts,read_metaobjects,write_metaobjects,read_metaobject_definitions,write_metaobject_definitions"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://market-shipping-threshold-app.vercel.app/api/auth/callback",
  "http://localhost:3000/api/auth/callback"
]

[app_proxy]
url = "https://market-shipping-threshold-app.vercel.app/api/proxy"
prefix = "apps"
subpath = "shipping-threshold"  