# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "07e2698ea30ed8908b2c6a7a1228e95c"
application_url = "https://example.com"
embedded = false
name = "Market Shipping Threshold App"

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_app_proxy,read_discounts,read_markets,read_shipping"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
